import mongoose from "mongoose";
import dotenv from "dotenv";
import Service from "../models/Service.js";
import connectDB from "../config/database.js";

dotenv.config();

const services = [
  // Electrical Services
  {
    name: "Electrical Wiring Repair",
    description: "Professional wiring repair and maintenance for your home",
    price: 2500,
    duration: "1-2 hours",
    category: "electrical",
    rating: 4.8,
    bookings: 245,
    emergency: false,
    tags: ["Wiring", "Safety Check", "Repair"],
    features: ["Complete wiring inspection", "Fault detection", "Safety certification"],
    popular: true,
  },
  {
    name: "Circuit Breaker Installation",
    description: "Install new circuit breakers for enhanced safety",
    price: 3500,
    duration: "2-3 hours",
    category: "electrical",
    rating: 4.9,
    bookings: 189,
    emergency: true,
    tags: ["Breaker", "Safety", "Installation"],
    features: ["Breaker installation", "Load testing", "Safety certification"],
  },
  {
    name: "Emergency Electrical Repair",
    description: "24/7 emergency electrical repair service",
    price: 5000,
    duration: "1 hour",
    category: "electrical",
    rating: 4.7,
    bookings: 567,
    emergency: true,
    tags: ["Emergency", "24/7", "Fast Response"],
    features: ["Immediate response", "Emergency diagnosis", "Quick fixes"],
    popular: true,
  },
  // Plumbing Services
  {
    name: "Leakage Repair",
    description: "Fix all types of water leaks in pipes and fixtures",
    price: 2000,
    duration: "1-2 hours",
    category: "plumbing",
    rating: 4.6,
    bookings: 312,
    emergency: true,
    tags: ["Leaks", "Water", "Repair"],
    features: ["Leak detection", "Pipe repair", "Water damage prevention"],
    popular: true,
  },
  {
    name: "Bathroom Plumbing",
    description: "Complete bathroom plumbing installation and repair",
    price: 4500,
    duration: "3-4 hours",
    category: "plumbing",
    rating: 4.8,
    bookings: 156,
    emergency: false,
    tags: ["Bathroom", "Installation", "Repair"],
    features: ["Fixture installation", "Drain unclogging", "Water pressure check"],
  },
  {
    name: "Water Heater Installation",
    description: "Install and repair water heating systems",
    price: 5500,
    duration: "2-3 hours",
    category: "plumbing",
    rating: 4.9,
    bookings: 98,
    emergency: false,
    tags: ["Water Heater", "Installation", "Repair"],
    features: ["Heater installation", "Temperature adjustment", "Maintenance tips"],
  },
  // Appliance Services
  {
    name: "Washing Machine Repair",
    description: "Expert repair for all washing machine brands",
    price: 3000,
    duration: "1-2 hours",
    category: "appliance",
    rating: 4.7,
    bookings: 203,
    emergency: false,
    tags: ["Washing Machine", "Repair", "Maintenance"],
    features: ["Motor check", "Drain pump repair", "Spin cycle fix"],
    popular: true,
  },
  {
    name: "Refrigerator Service",
    description: "Complete refrigerator repair and maintenance",
    price: 3500,
    duration: "1-2 hours",
    category: "appliance",
    rating: 4.8,
    bookings: 167,
    emergency: true,
    tags: ["Fridge", "Cooling", "Repair"],
    features: ["Compressor check", "Cooling test", "Gas refill"],
  },
  {
    name: "Oven & Microwave Repair",
    description: "Fix all types of ovens and microwave ovens",
    price: 2800,
    duration: "1 hour",
    category: "appliance",
    rating: 4.6,
    bookings: 134,
    emergency: false,
    tags: ["Oven", "Microwave", "Repair"],
    features: ["Heating element check", "Timer repair", "Safety inspection"],
  },
  // AC Services
  {
    name: "AC Gas Refill",
    description: "Refill refrigerant gas for better cooling",
    price: 4000,
    duration: "1-2 hours",
    category: "ac",
    rating: 4.9,
    bookings: 278,
    emergency: false,
    tags: ["AC", "Gas Refill", "Cooling"],
    features: ["Gas level check", "Leak test", "Cooling performance test"],
    popular: true,
  },
  {
    name: "AC Servicing",
    description: "Complete AC cleaning and maintenance",
    price: 2500,
    duration: "1-2 hours",
    category: "ac",
    rating: 4.7,
    bookings: 345,
    emergency: false,
    tags: ["AC", "Cleaning", "Maintenance"],
    features: ["Filter cleaning", "Coil cleaning", "Performance check"],
    popular: true,
  },
  {
    name: "AC Installation",
    description: "Professional AC installation service",
    price: 6000,
    duration: "3-4 hours",
    category: "ac",
    rating: 4.8,
    bookings: 89,
    emergency: false,
    tags: ["AC", "Installation", "New"],
    features: ["Unit installation", "Mounting", "Testing"],
  },
  // Carpentry Services
  {
    name: "Custom Furniture Making",
    description: "Design and build custom furniture for your home",
    price: 8000,
    duration: "2-3 days",
    category: "carpentry",
    rating: 4.9,
    bookings: 67,
    emergency: false,
    tags: ["Furniture", "Custom", "Wood"],
    features: ["Custom design", "Quality wood", "Finishing"],
  },
  {
    name: "Door & Window Repair",
    description: "Fix and maintain doors and windows",
    price: 2000,
    duration: "1-2 hours",
    category: "carpentry",
    rating: 4.5,
    bookings: 156,
    emergency: false,
    tags: ["Doors", "Windows", "Repair"],
    features: ["Hinge repair", "Lock fixing", "Frame adjustment"],
    popular: true,
  },
  // Painting Services
  {
    name: "Interior Wall Painting",
    description: "Professional interior painting services",
    price: 12000,
    duration: "2-3 days",
    category: "painting",
    rating: 4.7,
    bookings: 145,
    emergency: false,
    tags: ["Interior", "Painting", "Walls"],
    features: ["Wall preparation", "Quality paint", "Clean finish"],
    popular: true,
  },
  {
    name: "Exterior Painting",
    description: "Weather-resistant exterior painting",
    price: 18000,
    duration: "3-4 days",
    category: "painting",
    rating: 4.6,
    bookings: 89,
    emergency: false,
    tags: ["Exterior", "Painting", "Weather proof"],
    features: ["Surface prep", "Weather resistant paint", "Protective coating"],
  },
  // Security Services
  {
    name: "CCTV Installation",
    description: "Install security cameras for home protection",
    price: 15000,
    duration: "4-5 hours",
    category: "security",
    rating: 4.9,
    bookings: 234,
    emergency: false,
    tags: ["CCTV", "Security", "Camera"],
    features: ["Camera installation", "DVR setup", "Mobile viewing"],
    popular: true,
  },
  {
    name: "Smart Lock Installation",
    description: "Install digital and smart locks",
    price: 8500,
    duration: "1-2 hours",
    category: "security",
    rating: 4.8,
    bookings: 167,
    emergency: false,
    tags: ["Locks", "Smart Home", "Security"],
    features: ["Lock installation", "Access setup", "Mobile control"],
  },
  // Electronics/Tech Services
  {
    name: "Smart Home Setup",
    description: "Set up your smart home devices and automation",
    price: 7000,
    duration: "2-3 hours",
    category: "electronics",
    rating: 4.7,
    bookings: 123,
    emergency: false,
    tags: ["Smart Home", "Automation", "Setup"],
    features: ["Device pairing", "Automation setup", "Voice control"],
  },
  {
    name: "WiFi Network Setup",
    description: "Optimize your home WiFi network",
    price: 3500,
    duration: "1-2 hours",
    category: "electronics",
    rating: 4.6,
    bookings: 189,
    emergency: false,
    tags: ["WiFi", "Network", "Internet"],
    features: ["Router setup", "Coverage optimization", "Security config"],
    popular: true,
  },
  // Cleaning Services
  {
    name: "Deep Cleaning",
    description: "Complete home deep cleaning service",
    price: 8000,
    duration: "4-5 hours",
    category: "cleaning",
    rating: 4.8,
    bookings: 456,
    emergency: false,
    tags: ["Cleaning", "Deep Clean", "Home"],
    features: ["Full home cleaning", "Sanitization", "Organizing"],
    popular: true,
  },
  {
    name: "Sofa Cleaning",
    description: "Professional sofa and upholstery cleaning",
    price: 3500,
    duration: "2-3 hours",
    category: "cleaning",
    rating: 4.7,
    bookings: 234,
    emergency: false,
    tags: ["Sofa", "Upholstery", "Cleaning"],
    features: ["Stain removal", "Deep cleaning", "Odor removal"],
  },
  // Emergency Services
  {
    name: "24/7 Emergency Plumber",
    description: "Immediate plumbing assistance anytime",
    price: 6000,
    duration: "30-60 min",
    category: "emergency",
    rating: 4.9,
    bookings: 567,
    emergency: true,
    tags: ["Emergency", "24/7", "Plumbing"],
    features: ["Immediate dispatch", "Emergency fix", "All hours support"],
    popular: true,
  },
  {
    name: "Emergency Electrician",
    description: "Round-the-clock electrical emergency service",
    price: 6500,
    duration: "30-60 min",
    category: "emergency",
    rating: 4.8,
    bookings: 445,
    emergency: true,
    tags: ["Emergency", "24/7", "Electrical"],
    features: ["Quick response", "Emergency repair", "Safety first"],
    popular: true,
  }
];

const seedServices = async () => {
  try {
    await connectDB();
    
    // Clear existing services
    await Service.deleteMany({});
    console.log("📦 Cleared existing services");
    
    // Insert new services
    await Service.insertMany(services);
    console.log("🎉 Services seeded successfully!");
    
    process.exit(0);
  } catch (error) {
    console.error("Error seeding services:", error);
    process.exit(1);
  }
};

seedServices();